### ISSUE TITLE
The 'finished' boolean is not correct when partial results are requested

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-speech-recognition#16]
When partial results are desired and, the `finished` property should not return `true`.

**Comment by cmargulhano** [comment]
same here.
I think that is not corrected.

**Comment by EddyVerbruggen** [comment]
@cmargulhano Are you on 1.3.0? If so, please elaborate on the problem you're seeing.

**Comment by cmargulhano** [comment]
I understood that this would be useful to use start / stop functions programmatically. Am I wrong? Because I'd like to control this. Is it possible?

**Comment by EddyVerbruggen** [comment]
I'm not entirely sure what you're after, but I think [the code here will help you](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/tree/master/app/speech). You can also download the app that code is embedded in from the appstores first to see if that behaves according to your liking. For that, see the readme at [here](https://github.com/EddyVerbruggen/nativescript-pluginshowcase).

**Comment by cmargulhano** [comment]
First of all, my congratulations for these beautiful plugins. Somehow you help your copatriots, because I'm Brazilian and I'm building software for a Dutch company here in Brazil :)

**Comment by EddyVerbruggen** [comment]
Haha that's awesome. I hope you can make the client happy 😉
