### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by horeyes** [EddyVerbruggen/nativescript-speech-recognition#17]
Hello, 

I would suggest adding Angular "ChangeDetectionRef" class when the user triggers the startListening method. Otherwise the values would change out of sync. It took me a while to find the issue. I found the solution thanks to this link: https://blog.paulhalliday.io/2017/06/24/nativescript-speech-recognition/ where he implement that class to detect for changes.

**Comment by EddyVerbruggen** [comment]
Good point, thanks!

I've added two possible solutions to the readme.
