### ISSUE TITLE
Is it possible to save an audio file of the recognised speech?

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/nativescript-speech-recognition#20]
Not really an issue, more of a question. Do you think it is possible with this plugin to transcribe the audio as it is recording, and also save the audio itself to a file, so you have a recording of what the user originally said?

**Comment by EddyVerbruggen** [comment]
With `returnPartialResults` set to `true` you should get results streaming in while the user speaks. I don't know about recording audio.. would be a bit privacy sensitive.. perhaps try recording with `nativescript-audio` at the same time, but I expect it not to work because of privacy.
