### ISSUE TITLE
Error in request permission

### ISSUE THREAD

**Issue by juniorschen** [EddyVerbruggen/nativescript-speech-recognition#36]
hello I'm creating a new nativescript / angular 10 app and when using your plugin I'm having this problem:
![image](https://user-images.githubusercontent.com/46031261/90421964-8cc73780-e090-11ea-8d0a-f5f67a61f794.png)
I have this permissions in my app:
![image](https://user-images.githubusercontent.com/46031261/90422082-b5e7c800-e090-11ea-8518-cbab19d6bde2.png)
I took a look at your code, but I couldn't find any apparent problems (I don't have so much knowledge at the plugin level), could you help me?

**Comment by EddyVerbruggen** [comment]
I'm guessing you may be requesting permission before the app has fully started?

Can you try the demo app?

**Comment by juniorschen** [comment]
the problem ended up being the emulator
