### ISSUE TITLE
add support for language

### ISSUE THREAD

**Issue by GrEg00z** [EddyVerbruggen/nativescript-speech-recognition#5]
The option "locale" (for select speek language) is not implemented in the plugin.

I just added this in speech-recognition.android.js to make it works :

`intent.putExtra(android.speech.RecognizerIntent.EXTRA_LANGUAGE, "en"); `
**replaced by** 
`intent.putExtra(android.speech.RecognizerIntent.EXTRA_LANGUAGE, options.locale); `

Could you please fix it in the repo ? Thanks

**Comment by EddyVerbruggen** [comment]
Hmm, missed that TODO in the code. Thx for letting me know. Added to 1.1.3.
